data:
  dim: 3
  dataset: zju_mocap
  path: data/zju_mocap
  use_aug: false
  normalized_scale: true
  train_split: ['CoreView_315']
  val_split: ['CoreView_315']
  test_split: ['CoreView_315']
  train_views: ['1', '7', '13', '19', '2', '3', '4', '5', '6', '8', '9', '10', '11', '12', '14', '15', '16', '17', '18', '22', '23']
  val_views: ['2', '3', '4', '5', '6', '8', '9', '10', '11', '12', '14', '15', '16', '17', '18', '22', '23']
  test_views: ['2', '3', '4', '5', '6', '8', '9', '10', '11', '12', '14', '15', '16', '17', '18', '22', '23']
  train_subsampling_rate: 1
  train_start_frame: 0
  train_end_frame: 400
  val_subsampling_rate: 100000
  val_start_frame: 0
  val_end_frame: 400
  test_subsampling_rate: 30
  test_start_frame: 400
  test_end_frame: 1401
  num_fg_samples: 1024
  num_bg_samples:  1024
  off_surface_thr: 0.2
  box_margin: 0.05
  sample_reg_surface: true
  erode_mask: false
  inside_thr: 0.001
  sampling: default
  pose_dir: MPI-Limits_03009_op8_poses
  high_res: false
training:
  inside_weight: 10.0
